import type { Metadata } from "next";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-gray-900">
        <Header />
        <div className="flex">
          <Sidebar />
          <main className="pt-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
